# Generated by Django 5.1.1 on 2024-12-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_customuser_user_type_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_location', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('operating_from', models.TimeField()),
                ('operating_to', models.TimeField()),
                ('registration_number', models.CharField(max_length=100)),
                ('date_joined', models.DateField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_number', models.CharField(max_length=15)),
                ('gst_type', models.CharField(choices=[('registered_regular', 'Registered Business - Regular'), ('registered_composition', 'Registered Business - Composition'), ('unregistered', 'Unregistered Business'), ('overseas', 'Overseas'), ('consumer', 'Consumer'), ('sez', 'Special Economic Zone (SEZ)'), ('deemed_exports', 'Deemed Exports'), ('tax_deductor', 'Tax Deductor'), ('sez_developer', 'SEZ Developer')], max_length=50)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
