# Generated by Django 5.1.1 on 2024-12-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='hotel',
        ),
    ]
