# Generated by Django 5.1.1 on 2024-12-20 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_menu_added_by_menu_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='foodapp.hotelsignup'),
        ),
    ]
