# Generated by Django 5.1.1 on 2024-12-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_menu_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDisapproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('issue_type', models.CharField(choices=[('quality', 'Quality'), ('price', 'Price'), ('category', 'Category'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.menu')),
            ],
        ),
    ]
