# Generated by Django 5.1.1 on 2024-12-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsignup',
            name='license_copy',
            field=models.FileField(blank=True, null=True, upload_to='hotel_licenses/'),
        ),
        migrations.AddField(
            model_name='hotelsignup',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelsignup',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
