# Generated by Django 5.1.1 on 2025-01-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0015_hotelsignup_license_copy_hotelsignup_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelsignup',
            name='date_joined',
        ),
    ]
