# Generated by Django 5.1.1 on 2025-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0016_remove_hotelsignup_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsignup',
            name='restaurant_image',
            field=models.ImageField(blank=True, default='path_to_default_image.jpg', null=True, upload_to='hotel_images/'),
        ),
    ]
