# Generated by Django 5.1.1 on 2025-01-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0018_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_review',
            field=models.BooleanField(default=False),
        ),
    ]
