# Generated by Django 5.1.1 on 2025-01-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0025_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.menu'),
        ),
    ]
