# Generated by Django 5.1.1 on 2025-01-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0027_menu_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='original_price',
        ),
    ]
