# Generated by Django 5.1.1 on 2025-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0029_remove_review_restaurant_review_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsignup',
            name='restaurant_image',
            field=models.ImageField(blank=True, default='hotel_images/path_to_default_image.jpg', null=True, upload_to='hotel_images/'),
        ),
    ]
