# Generated by Django 5.1.1 on 2025-01-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0031_alter_hotelsignup_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderissuereport',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderissuereport',
            name='resolution_choice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
