# Generated by Django 5.1.1 on 2025-01-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0033_orderissuereport_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
