# Generated by Django 5.1.1 on 2025-01-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0035_recentsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to='foodapp.menu'),
        ),
    ]
