# Generated by Django 5.1.1 on 2025-01-21 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0039_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodapp.hotelsignup'),
        ),
    ]
