# Generated by Django 5.1.1 on 2025-01-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0045_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
