# Generated by Django 5.1.1 on 2025-01-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0047_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsignup',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelsignup',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
