# Generated by Django 5.1.1 on 2025-01-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0050_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
