# Generated by Django 5.1.1 on 2025-01-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0052_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'User'), ('3', 'Hotel'), ('4', 'Delivery_agent')], default='1', max_length=10),
        ),
    ]
