# Generated by Django 5.1.1 on 2025-01-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0055_order_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
