# Generated by Django 5.1.1 on 2025-01-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0058_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
